id: PE224DFB2
initial_creation_type: ocr
source_metadata:
  volumes:
    4ac0fb824b594ce3bd8b9aee1c94cc5b:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ལུགས་ཀྱི་བསྟན་བཅོས་སྐྱེ་བོ་གསོ་བའི་ཐིགས་པ།
      total_pages: 1872
      volume_number: 114
